<Project Sdk="Microsoft.NET.Sdk">

  <!-- Use the Microsoft Testing Platform selected in global.json. -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Kkdev92.StackChan.Gateway.AgentFramework.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\sdk\Kkdev92.StackChan.Gateway.AgentFramework\Kkdev92.StackChan.Gateway.AgentFramework.csproj" />
  </ItemGroup>

</Project>
