using System.Text;
using Kkdev92.StackChan.Gateway.AgentFramework.Models;
using Microsoft.Extensions.AI;
using Shouldly;
using Xunit;

namespace Kkdev92.StackChan.Gateway.AgentFramework.Tests;

/// <summary>
/// Verifies rules for structuring tool calls embedded in model response text.
/// </summary>
/// <remarks>
/// Converts Qwen and Phi-4 output formats that Foundry Local leaves in response text instead of
/// returning as <c>tool_calls</c> into tool calls that Agent Framework can process.
/// </remarks>
public sealed class TextToolCallChatClientTests
{
    [Fact]
    public void Qwen3_の出力からツール呼び出しを取り出す()
    {
        // The tool_call tag format generated by Qwen3.
        var buffer = new StringBuilder(
            """
            <tool_call>
            {"name": "set_stackchan_expression", "arguments": {"expression": "happy"}}
            </tool_call>
            """);

        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("set_stackchan_expression");
        calls[0].Arguments.ShouldNotBeNull();
        calls[0].Arguments!["expression"].ShouldBe("happy");

        text.Trim().ShouldBeEmpty();
    }

    [Fact]
    public void 閉じ波括弧が_1_つ多くても解析する()
    {
        // Accept the {...}} form sometimes generated by Qwen-family models.
        var buffer = new StringBuilder(
            """<tool_call>{"name": "nod_stackchan", "arguments": {}}}</tool_call>""");

        var (calls, _) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("nod_stackchan");
    }

    [Fact]
    public void Qwen25_のタグ形式も解析する()
    {
        var buffer = new StringBuilder(
            """<tools>{"name": "get_current_time", "arguments": {}}</tools>""");

        var (calls, _) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("get_current_time");
    }

    [Fact]
    public void 不正な_JSON_は本文のまま残す()
    {
        // Reproduce Qwen 2.5 output with an unterminated string.
        const string broken = """<tools>{"name": "set_stackchan_expression", "arguments": {"expression": "喜">}</tools>""";

        var buffer = new StringBuilder(broken);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.ShouldBeEmpty();

        // Preserve unparseable content as regular response text.
        text.ShouldBe(broken);
    }

    [Fact]
    public void ツール呼び出しがなければ_本文をそのまま返す()
    {
        const string plain = "こんにちは。今日はいい天気ですね。";

        var buffer = new StringBuilder(plain);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.ShouldBeEmpty();
        text.ShouldBe(plain);
    }

    [Fact]
    public void ツール呼び出し前後の本文は残す()
    {
        var buffer = new StringBuilder(
            """はい。<tool_call>{"name": "nod_stackchan", "arguments": {}}</tool_call>そうですね。""");

        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.Count.ShouldBe(1);
        text.ShouldBe("はい。そうですね。");
    }

    [Fact]
    public void 複数のツール呼び出しを取り出す()
    {
        var buffer = new StringBuilder(
            """
            <tool_call>{"name": "nod_stackchan", "arguments": {}}</tool_call>
            <tool_call>{"name": "set_stackchan_expression", "arguments": {"expression": "happy"}}</tool_call>
            """);

        var (calls, _) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.Count.ShouldBe(2);
        calls[0].Name.ShouldBe("nod_stackchan");
        calls[1].Name.ShouldBe("set_stackchan_expression");
    }

    [Fact]
    public void 複数チャンクにまたがるツール呼び出しを組み立てる()
    {
        // Reconstruct tags and JSON even when the stream arrives one character at a time.
        var buffer = new StringBuilder();
        var calls = new List<FunctionCallContent>();
        var text = new StringBuilder();

        const string whole =
            """あ<tool_call>{"name": "nod_stackchan", "arguments": {}}</tool_call>い""";

        foreach (var c in whole)
        {
            buffer.Append(c);

            var (chunkCalls, chunkText) = ToolCallText.DrainBuffer(
                buffer, flush: false);

            calls.AddRange(chunkCalls);
            text.Append(chunkText);
        }

        var (lastCalls, lastText) = ToolCallText.DrainBuffer(buffer, flush: true);
        calls.AddRange(lastCalls);
        text.Append(lastText);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("nod_stackchan");

        // Do not include an incomplete tag in text sent to the device.
        text.ToString().ShouldBe("あい");
    }

    [Fact]
    public void 開始タグの途中では_断片を保留する()
    {
        // Returning "<tool_" as text would make the device speak a tag fragment.
        var buffer = new StringBuilder("はい。<tool_");

        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: false);

        calls.ShouldBeEmpty();
        text.ShouldBe("はい。");

        // Keep the held fragment in the buffer so it can be combined with the next chunk.
        buffer.ToString().ShouldBe("<tool_");
    }

    [Fact]
    public void 開始タグになり得ない文字列は保留しない()
    {
        // Holding regular text would delay the start of a streaming response.
        var buffer = new StringBuilder("1 < 2 なので大丈夫です。");

        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: false);

        calls.ShouldBeEmpty();
        text.ShouldBe("1 < 2 なので大丈夫です。");
        buffer.Length.ShouldBe(0);
    }

    [Fact]
    public void 閉じタグがないまま終了したら_本文として返す()
    {
        const string unterminated = """"<tool_call>{"name": "nod_stackchan"""";

        var buffer = new StringBuilder(unterminated);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.ShouldBeEmpty();
        text.ShouldBe(unterminated);
    }

    [Theory]
    [InlineData("""{"name": "f", "arguments": {"n": 42}}""", 42L)]
    [InlineData("""{"name": "f", "arguments": {"n": true}}""", true)]
    [InlineData("""{"name": "f", "arguments": {"n": "x"}}""", "x")]
    public void ツール引数の_JSON_型を保持する(string json, object expected)
    {
        var buffer = new StringBuilder($"<tool_call>{json}</tool_call>");

        var (calls, _) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.Count.ShouldBe(1);
        calls[0].Arguments.ShouldNotBeNull();
        calls[0].Arguments!["n"].ShouldBe(expected);
    }

    [Fact]
    public void 同じ内容には_同じ呼び出し_ID_を割り当てる()
    {
        // A stable ID allows the tool result to be associated with its call.
        const string block =
            """<tool_call>{"name": "nod_stackchan", "arguments": {}}</tool_call>""";

        var first = ToolCallText
            .DrainBuffer(new StringBuilder(block), flush: true).Calls[0];

        var second = ToolCallText
            .DrainBuffer(new StringBuilder(block), flush: true).Calls[0];

        second.CallId.ShouldBe(first.CallId);
    }

    [Fact]
    public void 名前のない_JSON_はツール呼び出しに変換しない()
    {
        const string block = """<tool_call>{"arguments": {"x": 1}}</tool_call>""";

        var buffer = new StringBuilder(block);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.ShouldBeEmpty();
        text.ShouldBe(block);
    }

    // Qwen3 can return untagged JSON when /no_think is set. Convert it only when it names a declared
    // tool to avoid mistaking regular response text for a call.

    private static readonly HashSet<string> KnownTools = new(StringComparer.Ordinal)
    {
        "set_stackchan_expression",
        "nod_stackchan",
        "get_current_time",
    };

    [Fact]
    public void タグなしの_JSON_もツール呼び出しに変換する()
    {
        // The form generated by Qwen3 when /no_think is set.
        const string bare =
            """{"name": "set_stackchan_expression", "arguments": {"expression": "happy"}}""";

        var buffer = new StringBuilder(bare);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true, KnownTools);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("set_stackchan_expression");
        calls[0].Arguments!["expression"].ShouldBe("happy");
        text.ShouldBeEmpty();
    }

    [Fact]
    public void タグなし_JSON_の後ろに本文が続いても解析できる()
    {
        // Continue at the correct position after extracting JSON and shrinking the buffer.
        const string mixed =
            """{"name": "get_current_time", "arguments": {}}はい、いま調べますね。""";

        var buffer = new StringBuilder(mixed);

        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true, KnownTools);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("get_current_time");

        // Remove only converted JSON from the text and preserve the following sentence.
        text.ShouldBe("はい、いま調べますね。");
        buffer.Length.ShouldBe(0);
    }

    [Fact]
    public void 未宣言のツール名を持つ_JSON_は本文のまま残す()
    {
        // Do not lose text by converting a tool name that cannot be invoked.
        const string bare = """{"name": "launch_missiles", "arguments": {}}""";

        var buffer = new StringBuilder(bare);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true, KnownTools);

        calls.ShouldBeEmpty();
        text.ShouldBe(bare);
    }

    [Fact]
    public void ツール一覧がなければ_タグなし_JSON_を変換しない()
    {
        const string bare =
            """{"name": "set_stackchan_expression", "arguments": {"expression": "happy"}}""";

        var buffer = new StringBuilder(bare);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true);

        calls.ShouldBeEmpty();
        text.ShouldBe(bare);
    }

    [Fact]
    public void 通常の日本語本文は保留しない()
    {
        // Return text that does not begin with JSON to the stream immediately.
        const string plain = "はい、嬉しい顔にしますね。";

        var buffer = new StringBuilder(plain);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: false, KnownTools);

        calls.ShouldBeEmpty();
        text.ShouldBe(plain);
        buffer.Length.ShouldBe(0);
    }

    [Fact]
    public void 複数チャンクにまたがる_タグなし_JSON_を組み立てる()
    {
        const string bare =
            """{"name": "nod_stackchan", "arguments": {}}""";

        var buffer = new StringBuilder();
        var calls = new List<FunctionCallContent>();
        var text = new StringBuilder();

        foreach (var c in bare)
        {
            buffer.Append(c);

            var (chunkCalls, chunkText) = ToolCallText.DrainBuffer(
                buffer, flush: false, KnownTools);

            calls.AddRange(chunkCalls);
            text.Append(chunkText);
        }

        var (lastCalls, lastText) = ToolCallText.DrainBuffer(
            buffer, flush: true, KnownTools);

        calls.AddRange(lastCalls);
        text.Append(lastText);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("nod_stackchan");

        // Do not include incomplete JSON in text sent to the device.
        text.ToString().ShouldBeEmpty();
    }

    [Fact]
    public void JSON_で始まる本文でも_ツール呼び出しでなければ返す()
    {
        // Treat JSON that does not name a declared tool as regular response text.
        const string plain = """{"天気": "晴れ"} と表示されています。""";

        var buffer = new StringBuilder(plain);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true, KnownTools);

        calls.ShouldBeEmpty();
        text.ShouldBe(plain);
    }

    [Fact]
    public void Phi4_のタグと配列からツール呼び出しを取り出す()
    {
        // Phi-4 places an array inside <|tool_call|> and returns arguments as parameters.
        var buffer = new StringBuilder(
            """<|tool_call|>[{"name": "get_current_time", "parameters": {}}]<|/tool_call|>""");

        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true, KnownTools);

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("get_current_time");

        // Do not include tool-call JSON in text sent to the device.
        text.Trim().ShouldBeEmpty();
    }

    [Fact]
    public void Phi4_の_parameters_をツール引数として解析する()
    {
        var buffer = new StringBuilder(
            """
            <|tool_call|>[{"name": "set_stackchan_expression", "parameters": {"expression": "happy"}}]<|/tool_call|>
            """);

        var (calls, _) = ToolCallText.DrainBuffer(buffer, flush: true, KnownTools);

        calls.Count.ShouldBe(1);
        calls[0].Arguments.ShouldNotBeNull();
        calls[0].Arguments!["expression"].ShouldBe("happy");
    }

    [Fact]
    public void 表情マーカーを_JSON_配列として扱わない()
    {
        // Array support must not remove response markers such as [happy].
        const string spoken = "[happy]おはようございます。[neutral]よい天気です。";

        var buffer = new StringBuilder(spoken);
        var (calls, text) = ToolCallText.DrainBuffer(buffer, flush: true, KnownTools);

        calls.ShouldBeEmpty();
        text.ShouldBe(spoken);
    }

    [Fact]
    public async Task 構造化呼び出しと本文の呼び出しが重複しても_ツールは_1_度だけ実行する()
    {
        // When the same call appears in tool_calls and text, keep the structured call and remove the duplicate.
        using var fake = new FakeChatClient();
        fake.Rounds.Add(
        [
            new TextContent("""<|tool_call|>[{"name": "get_"""),
            new TextContent("""current_time", "parameters": {}}]<|/tool_call|>"""),
            new FunctionCallContent("server-id", "get_current_time", new Dictionary<string, object?>()),
        ]);

        using var client = new TextToolCallChatClient(fake);

        var options = new ChatOptions
        {
            Tools = [AIFunctionFactory.Create(() => "12:00", "get_current_time")],
        };

        var calls = new List<FunctionCallContent>();
        var spoken = new StringBuilder();

        await foreach (var update in client.GetStreamingResponseAsync(
            [new ChatMessage(ChatRole.User, "今何時ですか")],
            options,
            TestContext.Current.CancellationToken))
        {
            foreach (var content in update.Contents)
            {
                if (content is FunctionCallContent call)
                {
                    calls.Add(call);
                }
                else if (content is TextContent text)
                {
                    spoken.Append(text.Text);
                }
            }
        }

        calls.Count.ShouldBe(1);
        calls[0].Name.ShouldBe("get_current_time");
        spoken.ToString().ShouldNotContain("tool_call");
    }
}
