using Kkdev92.StackChan.Gateway.Abstractions;
using Kkdev92.StackChan.Gateway.TestKit;
using Xunit;

namespace Kkdev92.StackChan.Gateway.Conformance.Tests;

/// <summary>
/// Shares a response from an SDK-only endpoint across conformance tests.
/// </summary>
/// <remarks>
/// <para>
/// Positive and mutation tests use the same response generated by <see cref="SdkGatewayHost"/>.
/// This inspects actual serialized output instead of a handwritten sample.
/// </para>
/// <para>
/// The response has two sentences, each with more than 2,048 audio samples. This simultaneously tests
/// audio chunking, sequence numbers, and the rule that text appears only in each sentence's first event.
/// </para>
/// </remarks>
public sealed class ConformanceFixture : IAsyncLifetime
{
    /// <summary>PCM samples whose Base64 representation contains <c>+</c>.</summary>
    /// <remarks>
    /// The Base64 representation of <c>0xFB 0xF0</c> contains <c>+</c>. This value is fixed because the
    /// firmware cannot decode PCM if the JSON encoder emits <c>+</c> as a Unicode escape.
    /// </remarks>
    private static readonly short PlusProducingSample = unchecked((short)0xF0FB);

    public const string FirstSentence = "[happy]こんにちは、スタックちゃんです。";

    public const string SecondSentence = "[neutral]きょうは良い天気ですね。";

    public const string Transcript = "こんにちは、元気ですか";

    private SdkGatewayHost _host = null!;

    /// <summary>The response Content-Type.</summary>
    public string? ContentType { get; private set; }

    /// <summary>The response body bytes.</summary>
    public byte[] Body { get; private set; } = [];

    /// <inheritdoc />
    public async ValueTask InitializeAsync()
    {
        _host = await SdkGatewayHost.StartAsync();
        _host.SpeechToText.Result = Transcript;

        // Use a sentence longer than the seven-character suffix retained by the streaming formatter.
        _host.Agent.Fragments = [FirstSentence, SecondSentence];

        var samples = new short[2500];
        samples[0] = PlusProducingSample;
        _host.TextToSpeech.Result = new PcmAudio(
            samples,
            PcmAudio.CanonicalSampleRate,
            PcmAudio.CanonicalChannels);

        using var request = DeviceRequest.Speech(conversation: "conv-7");

        using var response = await _host.Client.SendAsync(
            request, TestContext.Current.CancellationToken);

        ContentType = response.Content.Headers.ContentType?.ToString();
        Body = await response.Content.ReadAsByteArrayAsync(TestContext.Current.CancellationToken);
    }

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        await _host.DisposeAsync();
    }
}

/// <summary>A collection that shares one response across conformance tests.</summary>
[CollectionDefinition(Name)]
public sealed class ConformanceCollection : ICollectionFixture<ConformanceFixture>
{
    public const string Name = "atoms3r-conformance";
}
